# Goal
uint8 TAKEOFF = 0
uint8 FLY_TO = 1
uint8 LAND = 2

uint8 task_type
geometry_msgs/Point target_pos
float32 target_yaw
float32 max_velocity
---
# Result
bool success
---
# Feedback
float32 distance_to_target