/**:
  ros__parameters:
    # 飞控连接参数，根据实际连接方式修改
    fcu_url: "/dev/ttyS6:921600"
    gcs_url: ""
    tgt_system: "1"
    tgt_component: "1"
    fcu_protocol: "v2.0"
    respawn_mavros: "false"
    # 多机协同时需要有不同的命名，否则会冲突
    namespace: "mavros"